repos:
  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
      - id: autopep8
        args: ["--in-place", "--aggressive", "--aggressive"]

  - repo: local
    hooks:
      - id: quality-checks
        name: Code Quality Checks
        entry: ./quality-checks/run_all.py
        language: script
        types: [shell]
