version: "3.8"

x-airflow-common: &airflow-common
  image: amazon-mwaa/airflow:2.9.0
  restart: always
  environment:
    # AWS credentials
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    AWS_REGION: ${AWS_REGION}
    AWS_DEFAULT_REGION: ${AWS_REGION}

    # Core configuration
    MWAA__CORE__REQUIREMENTS_PATH: "/usr/local/airflow/requirements/requirements.txt"

    # Database configuration
    MWAA__DB__POSTGRES_HOST: "postgres"
    MWAA__DB__POSTGRES_PORT: "5432"
    MWAA__DB__POSTGRES_USER: "airflow"
    MWAA__DB__POSTGRES_PASSWORD: "airflow"
    MWAA__DB__POSTGRES_DB: "airflow"
    MWAA__DB__POSTGRES_SSLMODE: "prefer"

    # SQS configuration
    MWAA__SQS__CREATE_QUEUE: True
    MWAA__SQS__CUSTOM_ENDPOINT: http://sqs:9324
    MWAA__SQS__QUEUE_URL: http://sqs:9324/000000000000/celery-queue
    MWAA__SQS__USE_SSL: False

  volumes:
    - ./dags:/usr/local/airflow/dags
    - ./plugins:/usr/local/airflow/plugins
    - ./requirements:/usr/local/airflow/requirements
  depends_on: &airflow-common-depends-on
    postgres:
      condition: service_healthy
    sqs:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    container_name: mwaa-280-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432

  sqs:
    image: softwaremill/elasticmq:latest
    healthcheck:
      # https://github.com/softwaremill/elasticmq/issues/776#issuecomment-1582527921
      test: ["CMD-SHELL", "wget -q -S -O - 127.0.0.1:9324/?Action=ListQueues"]
      interval: 10s
      retries: 5
      start_period: 5s
    ports:
      - 9324:9324
      - 9325:9325
    expose:
      - 9324
      - 9325

  # TODO Create a local CloudWatch endpoint to allow the customer to use this Docker Compose file without a real AWS account.
  # TODO Create a local CloudWatch Metrics endpoint to allow the customer to use this Docker Compose file without a real AWS account.

  spy:
    <<: *airflow-common
    command: spy
    container_name: mwaa-280-spy

  webserver:
    <<: *airflow-common
    command: webserver
    container_name: mwaa-280-webserver
    ports:
      - 8080:8080
    expose:
      - 8080

  scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: mwaa-280-scheduler

  worker:
    <<: *airflow-common
    command: worker
    container_name: mwaa-280-worker

volumes:
  postgres-db-volume:
    name: "mwaa-280-db-volume"
