exclude = [
    ".venv",
    # sqs_broker.py is code largely taken from Kombu (part of Celery) with minor changes
    # from us. We want to respect the original code and not make a lot of changes, and
    # just mark the changes we make, hence we ignore linting it.
    "python/mwaa/celery/sqs_broker.py"
]

[lint]
select = [
    # Enable pydocstyle rules to enforce documentation
    "D1"
]

